version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  nx: nrwl/nx@1.0.0

executors:
  default:
    docker:
      - image: circleci/node:current

commands:
  install-dependencies:
    steps:
      - run: npm install
  cache-dependencies:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  restore-dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  build-app:
    steps:
      - run: npm run build web --verbose && npm run build infrastructure --verbose
  deploy-app:
    steps:
      - run: npm run deploy

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - build-app
      - persist_to_workspace:
          root: ~/
          paths:
            - project/dist
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - restore-dependencies
      - install-dependencies
      - cache-dependencies
      - attach_workspace:
          at: ~/
      - aws-cli/setup
      - deploy-app

workflows:
  version: 2
  ci-master:
    jobs:
      - build:
          context: aws-youtube-api-keys
          filters:
            branches:
              only:
                - master
      - deploy:
          context: aws-account
          requires:
            - build
          filters:
            branches:
              only:
                - master
